import { StationScene } from "./StationLesson.jsx";
import { Volume2 as PlaybackIcon } from "lucide-react";
import React, { useState } from 'react';
import { phrasalStories } from '../../../shared/phrasal-stories.js';
import { episodes } from '../../../shared/phrasal-episodes.js';

function StoryScene({scene}) {
  return <svg className="story-scene" viewBox="0 0 600 220" role="img" aria-label={`Minh họa ${scene}`}>
    <rect width="600" height="220" rx="22" fill="#e3efe7"/>
    <circle cx="495" cy="48" r="30" fill="#f5c16e"/>
    <path d="M0 185Q130 140 270 185T600 170V220H0Z" fill="#b4d1bd"/>
    {scene === 'friends' ? <><path d="M120 170H440M140 155V200M420 155V200" stroke="#b08462" strokeWidth="12"/><circle cx="235" cy="90" r="24" fill="#dca378"/><path d="M200 150Q198 112 235 112Q272 112 270 150" fill="#728dba"/><circle cx="345" cy="90" r="24" fill="#be825f"/><path d="M310 150Q308 112 345 112Q382 112 380 150" fill="#ce917d"/><path d="M85 180V100" stroke="#688865" strokeWidth="12"/><circle cx="85" cy="75" r="45" fill="#87b38c"/></> : scene === 'travel' ? <><path d="M50 165L160 40 265 165M205 165L345 60 460 165" fill="#88afa5"/><rect x="375" y="108" width="130" height="67" rx="14" fill="#f5bc80"/><rect x="390" y="119" width="38" height="25" fill="#fff7dc"/><rect x="439" y="119" width="44" height="25" fill="#fff7dc"/><circle cx="400" cy="176" r="13" fill="#334b48"/><circle cx="480" cy="176" r="13" fill="#334b48"/></> : <><rect x="65" y="35" width="105" height="112" rx="42" fill="#faf6e6"/><path d="M117 36V146M66 95H169" stroke="#94b7aa" strokeWidth="5"/><rect x="210" y="143" width="235" height="12" rx="6" fill="#ae7859"/><path d="M230 155V210M425 155V210" stroke="#ae7859" strokeWidth="9"/><circle cx="290" cy="85" r="24" fill="#dca378"/><path d="M253 140Q250 106 286 108Q324 106 325 140" fill="#537e70"/><path d="M267 75Q293 42 314 78" fill="#493e3a"/><rect x="340" y="107" width="61" height="37" rx="4" fill={scene === 'work' ? '#8695b3' : '#f0ba7c'}/><path d="M505 180V106M505 142Q465 134 477 107Q510 113 505 142M505 120Q540 107 535 80Q504 85 505 120" stroke="#508c67" strokeWidth="8" fill="none"/></>}
  </svg>;
}
export default function PhrasalStories({speak,onStation,illustration: Scene = StoryScene}) {
  const [selected,setSelected] = useState(null), [chapter,setChapter]=useState(0);
  const base=phrasalStories[selected];
  const chapters=base ? [base,...episodes.filter(e=>e[0]===base.id).map((e,i)=>({...base,id:base.id+'-'+i,title:e[1],text:e[2],dialogues:e[3]}))] : [];
  return <section className="phrasal-stories"><p className="phrasal-intro">Chọn một tình huống để bắt đầu. Mỗi bài chỉ tập trung vào một nhóm cụm từ nhỏ.</p>{selected===null ? <div className="story-group-grid">{onStation && <button className="station-entry" onClick={onStation}><StationScene/><span className="eyebrow">BÀI TÌNH HUỐNG</span><h3>Đón bạn ở ga</h3><p>Hẹn chỗ đón và thu xếp chuyến xe về.</p><small>3 cụm · 4 câu hỏi · lưu theo tài khoản</small><p className="group-words">pick up · set off · get back</p><strong>Bắt đầu →</strong></button>}{phrasalStories.map((s,i)=><button key={s.id} onClick={()=>{setSelected(i);setChapter(0);}}><Scene scene={s.scene} title={s.title}/><h3>{s.title}</h3><p>{s.context}</p><small>3 đoạn đọc · 2 hội thoại · 5 cụm từ</small><p className="group-words">{s.terms.slice(0,3).map(t=>t[0]).join(' · ')}</p><strong>Vào tình huống →</strong></button>)}</div> : <><button className="text-button" onClick={()=>setSelected(null)}>← Các nhóm tình huống</button><div className="story-tabs">{chapters.map((s,i)=><button key={s.id} className={chapter===i?'active':''} onClick={()=>setChapter(i)}>{i+1}. {s.title}</button>)}</div><Story illustration={Scene} key={chapters[chapter].id} story={chapters[chapter]} speak={speak}/></>}</section>;
}
function Story({story:s,speak,illustration: Scene = StoryScene}) {
  const [term,setTerm]=useState(null), [hidden,setHidden]=useState(false), [answers,setAnswers]=useState({}), [checked,setChecked]=useState(false);
  const parts=s.text.split(/\*\*(.*?)\*\*/g);
  return <><StoryScene scene={s.scene}/><h3>{s.title}</h3><p>{s.context}</p><div className="story-actions"><button className="subtle-button" onClick={()=>speak(s.text.replaceAll('**',''))} aria-label="Phát âm thanh" title="Phát âm thanh"><PlaybackIcon size={20} aria-hidden="true" /></button><button className="subtle-button" onClick={()=>{setHidden(!hidden);setChecked(false);setAnswers({});setTerm(null);}}>{hidden?'Đọc lại đoạn văn':'Ẩn cụm từ · thử nhớ'}</button></div><p className="story-reading">{parts.map((part,i)=>i%2 ? hidden ? <input key={i} aria-label={`Cụm từ thứ ${(i+1)/2}`} value={answers[i]||''} onChange={e=>setAnswers({...answers,[i]:e.target.value})} placeholder="…"/> : <button key={i} onClick={()=>setTerm(s.terms.find(t=>t[0]===part))}><strong>{part}</strong></button> : part)}</p>{term&&<aside className="hint-box" role="status"><strong>{term[0]} · {term[1]}</strong><p>{term[2]}</p><button className="text-button" onClick={()=>speak(term[0])} aria-label="Phát âm thanh" title="Phát âm thanh"><PlaybackIcon size={20} aria-hidden="true" /></button></aside>}{hidden&&<><button className="primary" onClick={()=>setChecked(true)}>Kiểm tra đoạn đọc</button>{checked&&<div className="hint-box" role="status">{parts.map((part,i)=>i%2 ? <p key={i}>{(answers[i]||'').trim().toLowerCase()===part.toLowerCase()?'✓':'↻'} {part} — {s.terms.find(t=>t[0]===part)?.[1]}</p>:null)}<small>Bài đọc tự luyện; chưa cộng vào mức thành thạo hoặc tiến độ tài khoản.</small></div>}</>}{s.dialogues && <section className="story-dialogue"><h3>Thử nhập vai cùng một người bạn</h3><p>Đọc vai A, thử trả lời rồi mở vai B.</p>{s.dialogues.map(([a,b],i)=><div key={i}><p><b>A</b> {a} <button className="text-button" onClick={()=>speak(a)} aria-label="Phát âm thanh" title="Phát âm thanh"><PlaybackIcon size={20} aria-hidden="true" /></button></p><details><summary>Mở lời đáp của B</summary><p><b>B</b> {b} <button className="text-button" onClick={()=>speak(b)} aria-label="Phát âm thanh" title="Phát âm thanh"><PlaybackIcon size={20} aria-hidden="true" /></button></p></details></div>)}</section>}<details><summary>Từ vựng & lưu ý cách dùng</summary>{s.terms.map(([en,vi,note])=><p key={en}><strong>{en}</strong> — {vi}<br/><small>{note}</small></p>)}</details><small>Đoạn đọc và minh họa được viết mới cho ứng dụng. Tham khảo ngữ pháp: <a href="https://learnenglish.britishcouncil.org/free-resources/grammar/b1-b2/phrasal-verbs" target="_blank" rel="noreferrer">British Council</a>.</small></>;
}
