import { readingLessons } from "./reading-lessons.js";

// Independently authored syllabus. IDs are stable; increment version when grading changes.
const grammar = [
  [
    "coffee-preferences",
    "Sở thích và lựa chọn",
    "Prefer A to B; would prefer + to-infinitive cho lựa chọn cụ thể.",
    "I prefer quiet cafés to crowded bars.",
    "Chọn giới từ: I prefer tea ____ coffee.",
    "to",
    "Prefer A to B; không dùng than trong cấu trúc này.",
    "food",
  ],
  [
    "exchange-size",
    "Kể sự việc đã xảy ra",
    "Dùng past simple khi kể sự việc hoàn tất tại một thời điểm quá khứ.",
    "I bought this jacket yesterday.",
    "Điền dạng quá khứ của buy: I ____ this yesterday.",
    "bought",
    "Buy là động từ bất quy tắc: buy → bought.",
    "shopping",
  ],
  [
    "station-signs",
    "Câu hỏi gián tiếp",
    "Could you tell me + từ hỏi + chủ ngữ + động từ; không đảo trợ động từ bên trong.",
    "Could you tell me where the lift is?",
    "Điền một từ: Could you tell me where the lift ____? (dùng be ở hiện tại)",
    "is",
    "Sau where trong câu hỏi gián tiếp, dùng the lift is.",
    "travel",
  ],
  [
    "work-followup",
    "Người đang phụ trách",
    "Be in charge of + danh từ hoặc V-ing; dùng để xác định trách nhiệm.",
    "Mina is in charge of checking the report.",
    "Điền giới từ: Who is in charge ____ this task?",
    "of",
    "In charge of là cụm cố định.",
    "work",
  ],
  [
    "home-cooking",
    "Danh từ không đếm được",
    "Dùng much với danh từ không đếm được; many với danh từ đếm được số nhiều.",
    "We do not have much cream left.",
    "Chọn much hoặc many: We do not have ____ cream left.",
    "much",
    "Cream dùng như nguyên liệu là danh từ không đếm được trong câu này.",
    "home",
  ],
  [
    "reschedule-friends",
    "Sắp xếp một cuộc hẹn",
    "Hiện tại tiếp diễn có thể diễn đạt kế hoạch tương lai đã thu xếp.",
    "We are meeting on Saturday morning.",
    "Điền be: We ____ meeting on Saturday.",
    "are",
    "Chủ ngữ we dùng are trong hiện tại tiếp diễn.",
    "plans",
  ],
  [
    "clinic-appointment",
    "Lời đề nghị lịch sự",
    "Could you + động từ nguyên mẫu; không thêm to.",
    "Could you explain this question?",
    "Điền dạng đúng của explain: Could you ____ this question?",
    "explain",
    "Sau could dùng động từ nguyên mẫu không to.",
    "health",
  ],
  [
    "hotel-arrival",
    "Hành lý và lượng từ",
    "Luggage là danh từ không đếm được. Dùng a piece of luggage khi cần nói một kiện.",
    "How much luggage do you have?",
    "Chọn much hoặc many: How ____ luggage do you have?",
    "much",
    "Không dùng luggages hoặc how many luggage.",
    "travel",
  ],
  [
    "library-study",
    "Mượn và cho mượn",
    "Borrow something from someone; lend something to someone.",
    "I borrowed a book from the library.",
    "Điền giới từ: I borrowed a book ____ the library.",
    "from",
    "Borrow from chỉ nguồn cho mượn.",
    "learning",
  ],
  [
    "repair-laptop",
    "Đại từ với phrasal verb tách được",
    "Với turn on, đại từ tân ngữ nằm giữa động từ và tiểu từ.",
    "Please turn it on.",
    "Sắp xếp turn / it / on thành cụm đúng.",
    "turn it on",
    "Dùng turn it on, không dùng turn on it.",
    "tech",
  ],
  [
    "games-newcomer",
    "Thay phiên làm gì",
    "Take turns + V-ing để nói về hành động thay phiên nhau.",
    "We take turns choosing a card.",
    "Điền dạng của choose: We take turns ____ a card.",
    "choosing",
    "Sau take turns dùng V-ing.",
    "entertainment",
  ],
  [
    "community-donations",
    "Đề nghị phụ giúp",
    "Help out with + danh từ/V-ing; help someone + động từ nguyên mẫu cũng có thể dùng.",
    "Can I help out with sorting the clothes?",
    "Điền giới từ: Can I help out ____ the boxes?",
    "with",
    "Help out with a task = phụ giúp một nhiệm vụ.",
    "help",
  ],
  [
    "b2-project-scope",
    "Điều kiện và cam kết",
    "Provided that nêu điều kiện. Trong mệnh đề điều kiện tương lai thông thường, dùng hiện tại đơn.",
    "We will launch provided that the tests pass.",
    "Điền pass ở dạng đúng: We will launch provided that the test ____.",
    "passes",
    "The test số ít dùng passes; không dùng will pass trong điều kiện này.",
    "work",
  ],
  [
    "b2-hotel-complaint",
    "Nhượng bộ khi phản ánh",
    "Although + mệnh đề hoàn chỉnh; despite + danh từ/V-ing.",
    "Although I requested a quiet room, the room was noisy.",
    "Chọn although hoặc despite: ____ my request, the room was noisy.",
    "despite",
    "My request là cụm danh từ, nên dùng despite.",
    "travel",
  ],
  [
    "b2-evidence",
    "Diễn đạt kết luận thận trọng",
    "May/might/could + động từ nguyên mẫu cho khả năng; tránh biến suy luận thành điều chắc chắn.",
    "The sample may explain the difference.",
    "Điền dạng của explain: The sample may ____ the difference.",
    "explain",
    "Sau may dùng nguyên mẫu; mức chắc chắn vẫn là khả năng.",
    "learning",
  ],
  [
    "b2-digital-boundaries",
    "Ngoại lệ và điều kiện phủ định",
    "Unless thường mang nghĩa if not; không thêm not nếu điều đó làm đảo nghĩa dự định.",
    "Do not call unless the issue is urgent.",
    "Điền unless hoặc despite: Do not call ____ the issue is urgent.",
    "unless",
    "Unless + mệnh đề: đừng gọi trừ khi có việc khẩn.",
    "phone",
  ],
  [
    "b2-community-choice",
    "So sánh điều khả thi",
    "Would + động từ nguyên mẫu để nói kết quả giả định, thường đi với if + quá khứ đơn.",
    "If we had more volunteers, we would offer another session.",
    "Điền had hoặc have: If we ____ more volunteers, we would offer another session.",
    "had",
    "Điều kiện giả định hiện tại dùng if + past simple, would + động từ.",
    "help",
  ],
  [
    "b2-interview-example",
    "Nhìn lại và đề xuất khác đi",
    "Would + động từ nguyên mẫu cho cách mình sẽ xử lý trong tình huống giả định.",
    "I would prepare a backup process next time.",
    "Điền dạng prepare: I would ____ a backup process.",
    "prepare",
    "Sau would dùng động từ nguyên mẫu không to.",
    "interview",
  ],
];
export const courseUnits = grammar.map(
  ([key, title, rule, example, prompt, answer, explanation, topic]) => {
    const reading = readingLessons.find((l) => l.id === `reading-${key}-v1`);
    if (!reading) throw new Error(`Missing course reading: ${key}`);
    return {
      id: `course-${key}`,
      version: 1,
      level: key.startsWith("b2-") ? "B2" : "B1",
      topic,
      reading,
      grammar: { title, rule, example },
      questions: [
        {
          id: "meaning",
          mode: "choice",
          prompt: reading.question.prompt,
          options: reading.question.options,
          answer: reading.question.options[reading.question.answer],
          explanation: reading.question.explanation,
        },
        { id: "recall", mode: "recall", ...reading.recall },
        { id: "grammar", mode: "grammar", prompt, answer, explanation },
      ],
    };
  },
);
export const courses = [
  {
    id: "b1",
    level: "B1",
    title: "B1 · Giao tiếp có nền tảng",
    description:
      "Từ các tình huống A2–B1, xây cách nói rõ ràng và dùng đúng cấu trúc.",
    units: courseUnits.filter((u) => u.level === "B1"),
  },
  {
    id: "b2",
    level: "B2",
    title: "B2 · Diễn đạt có chiều sâu",
    description:
      "Cân nhắc, thương lượng và giải thích ý kiến với sắc thái phù hợp.",
    units: courseUnits.filter((u) => u.level === "B2"),
  },
];
export const getCourseUnit = (id) => courseUnits.find((u) => u.id === id);
