export const photoSources = {
  'pv-dishes': {
    id: 7641231,
    author: 'MART PRODUCTION',
    slug: 'person-washing-dishes',
    alt: 'Cận cảnh hai tay rửa chiếc đĩa dưới vòi nước ở bồn bếp',
    position: '50% 55%',
    checkedAt: '2026-09-28',
  },
  'pv-fitting': {
    id: 7668395,
    author: 'MART PRODUCTION',
    slug: 'a-woman-looking-at-the-mirror',
    alt: 'Người phụ nữ thử trang phục và xem độ vừa trước gương trong cửa hàng',
    position: '50% 58%',
    checkedAt: '2026-09-28',
  },
  health: {
    id: 8413204,
    author: "SHVETS production",
    slug: "doctor-and-patient-talking-in-office",
    alt: "Bác sĩ và người đến khám trao đổi trong phòng khám",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  learning: {
    id: 9572630,
    author: "Tima Miroshnichenko",
    slug: "college-students-reading-a-book-inside-the-library",
    alt: "Hai sinh viên cùng đọc sách trong thư viện",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  hotel: {
    id: 3768095,
    author: "Andrea Piacquadio",
    slug: "selective-focus-photo-of-reception-signage",
    alt: "Chuông và biển Reception tại quầy lễ tân khách sạn",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  interview: {
    id: 4344878,
    author: "Edmond Dantès",
    slug: "woman-in-a-job-interview",
    alt: "Ứng viên trao đổi trong buổi phỏng vấn tại văn phòng",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  plans: {
    id: 19399416,
    author: "Walls.io",
    slug: "page-from-a-calendar-planner",
    alt: "Trang sổ lịch với kế hoạch viết tay",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  phone: {
    id: 4240495,
    author: "Ivan S",
    slug: "woman-talking-on-phone",
    alt: "Người phụ nữ gọi điện và cầm sổ ghi chép",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  tech: {
    id: 16385070,
    author: "Mediahooch Pixels",
    slug: "a-woman-repairing-laptop",
    alt: "Kỹ thuật viên dùng dụng cụ sửa máy tính xách tay",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  entertainment: {
    id: 8111352,
    author: "Pavel Danilyuk",
    slug: "friends-playing-a-board-game-together",
    alt: "Nhóm bạn chơi trò chơi bàn cùng nhau",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  feelings: {
    id: 37129604,
    author: "Huỳnh Như Mavi",
    slug: "woman-writing-in-journal-by-a-window",
    alt: "Cận cảnh người phụ nữ cúi xuống viết vào sổ",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  help: {
    id: 7156193,
    author: "Gustavo Fring",
    slug: "handing-out-of-box-of-donations",
    alt: "Hai người trao nhận thùng quần áo và đồ chơi quyên góp",
    position: "50% 50%",
    checkedAt: "2026-09-12",
  },
  cafe: {
    id: 27407741,
    author: "Ryon Justin Moran",
    slug: "a-coffee-cup-sitting-on-a-wooden-table",
    alt: "Cốc cà phê latte trên bàn gỗ cạnh cửa sổ",
    position: "50% 82%",
  },
  shop: {
    id: 5864244,
    author: "Rachel Claire",
    slug: "women-shopping-in-clothing-store",
    alt: "Khách xem quần áo trên giá trong cửa hàng",
    position: "50% 50%",
  },
  bus: {
    id: 9360429,
    author: "Abhinav Toppo",
    slug: "empty-platform-in-train-station",
    alt: "Sân ga với đường ray, đồng hồ và biển chỉ dẫn thang máy",
    position: "50% 65%",
  },
  work: {
    id: 6146812,
    author: "Diva Plavalaguna",
    slug: "people-having-a-meeting-at-the-office",
    alt: "Nhóm đồng nghiệp trao đổi quanh bàn có máy tính xách tay",
    position: "50% 45%",
  },
  home: {
    id: 5883734,
    author: "thiha soe",
    slug: "a-kitchen-interior",
    alt: "Căn bếp có bồn rửa, tủ đựng đồ và lò vi sóng",
    position: "50% 50%",
  },
  friends: {
    id: 8937491,
    author: "Thirdman",
    slug: "friends-having-coffee-together",
    alt: "Hai người trò chuyện bên bàn cà phê gần cửa sổ",
    position: "50% 40%",
  },
};
for (const [key, photo] of Object.entries(photoSources))
  Object.assign(photo, {
    src: `/photos/${key}.webp`,
    url: `https://www.pexels.com/photo/${photo.slug}-${photo.id}/`,
    license: "Pexels License",
    licenseUrl: "https://www.pexels.com/license/",
    checkedAt: photo.checkedAt || "2026-09-11",
    modifications:
      "Resized to maximum width 1200px, converted to WebP; display crop only.",
  });
