// Original teaching stories. Grammar reference: British Council, Phrasal verbs.
export const phrasalStories = [
  { id:'morning', title:'Buổi sáng không vội', scene:'home', context:'Mai kể cách chuẩn bị trước khi ra khỏi nhà.',
    text:'I usually **wake up** before my alarm. Today I **get up** slowly and open the curtains. Before breakfast, I **put on** a comfortable shirt. There is a little mess from dinner, so I **clean up** the kitchen. Then I **head out** with my bag. A calm morning makes the rest of my day easier.',
    terms:[['wake up','thức giấc','Khác get up: bạn có thể tỉnh nhưng vẫn nằm trên giường.'],['get up','ra khỏi giường','Không cần tân ngữ trong nghĩa này.'],['put on','mặc vào','Có thể tách: put it on.'],['clean up','dọn dẹp','Có thể nói clean it up.'],['head out','ra ngoài, lên đường','Nhấn mạnh bắt đầu rời đi.']] },
  { id:'team', title:'Cùng giải quyết vấn đề', scene:'work', context:'Một nhóm nhỏ chuẩn bị buổi giới thiệu sản phẩm.',
    text:'Our team has a problem with the demo. We need to **look into** the error before Friday. During lunch, we **come up with** a simpler plan. I **write down** the main steps so nobody forgets them. We **carry out** a quick test together. If it works, we will **set up** another meeting to show everyone the result.',
    terms:[['look into','tìm hiểu, điều tra','Không tách: look into it.'],['come up with','nghĩ ra','Giữ cả cụm: come up with a plan.'],['write down','ghi lại','Có thể tách: write it down.'],['carry out','thực hiện','Dùng với kế hoạch, nhiệm vụ hoặc thử nghiệm.'],['set up','sắp xếp, thiết lập','Trong đoạn này: tổ chức một cuộc họp.']] },
  { id:'trip', title:'Chuyến đi cuối tuần', scene:'travel', context:'Hai người bạn đi nghỉ và thu xếp chỗ ở.',
    text:'We **set off** early to avoid traffic. At the hotel, we **check in** and leave our bags in the room. We want to **look around** the old town before dinner. The next morning, we **check out** before eleven. On the way home, we **stop by** a small bakery to buy a present for our neighbour.',
    terms:[['set off','khởi hành','Không cần tân ngữ trong nghĩa bắt đầu chuyến đi.'],['check in','làm thủ tục nhận phòng','Cũng dùng khi làm thủ tục chuyến bay.'],['look around','đi xem xung quanh','Khám phá một địa điểm.'],['check out','làm thủ tục trả phòng','Cụm này có nghĩa khác; ở đây là rời khách sạn.'],['stop by','ghé qua','Thường là một chuyến ghé ngắn.']] },
  { id:'friends', title:'Một buổi tối cùng bạn', scene:'friends', context:'Bạn rủ một người bạn đang buồn ra ngoài trò chuyện.',
    text:'My friend has had a difficult week. I suggest that we **eat out** somewhere quiet. We can **catch up** over dinner and talk about our lives. Later, we **hang out** in the park. I hope the fresh air will help her **cheer up**. We promise to **keep in touch** even when work gets busy again.',
    terms:[['eat out','ăn ở ngoài','Ăn tại quán thay vì ở nhà.'],['catch up','hỏi thăm chuyện gần đây','Trong đoạn này: cập nhật tình hình của nhau.'],['hang out','dành thời gian thư giãn cùng nhau','Cách nói thân mật.'],['cheer up','vui lên','Có thể nói cheer someone up: làm ai vui lên.'],['keep in touch','giữ liên lạc','Đây là cụm cố định, không phải phrasal verb; học kèm theo ngữ cảnh.']] },
];
