// Choice-based role play, deliberately authored; not an AI conversation or speaking assessment.
const step = (line, prompt, answer, wrong, why) => ({
  line,
  prompt,
  options: [answer, ...wrong],
  answer,
  why,
});
export const scenarios = [
  {
    id: "food",
    title: "Một ly cà phê đúng ý",
    role: "Bạn là khách tại quán cà phê.",
    icon: "Coffee",
    steps: [
      step(
        "Hi! What can I get you?",
        "Gọi một latte đá, lịch sự.",
        "I'd like an iced latte, please.",
        ["I want you to drink coffee.", "You should have a latte."],
        "“I’d like …, please” là mẫu gọi món lịch sự; “I want you to …” lại yêu cầu người kia làm việc gì đó.",
      ),
      step(
        "Of course. Would you like any sugar?",
        "Bạn muốn không đường.",
        "No sugar, please.",
        ["No, I am not sugar.", "I have no sweet."],
        "Dùng “No + thành phần, please” để yêu cầu bỏ thành phần đó.",
      ),
      step(
        "For here or to go?",
        "Bạn muốn mang đi.",
        "To go, please.",
        ["I am going yesterday.", "Go yourself, please."],
        "“To go” chỉ đồ mang đi, đối lập với “for here” là dùng tại quán.",
      ),
    ],
  },
  {
    id: "work",
    title: "Cuộc họp cần đổi lịch",
    role: "Bạn đang nhắn cho đồng nghiệp.",
    icon: "BriefcaseBusiness",
    steps: [
      step(
        "Are we still meeting at two?",
        "Bạn có việc đột xuất.",
        "Something has come up. Could we reschedule?",
        ["Something is coming to my house.", "You must cancel everything."],
        "“Something has come up” giải thích việc phát sinh, rồi đề nghị đổi lịch.",
      ),
      step(
        "Sure. How about Friday morning?",
        "Bạn thấy lịch mới phù hợp.",
        "That works for me.",
        ["That works on me.", "That is my work."],
        "“That works for me” dùng để đồng ý một phương án hoặc thời gian.",
      ),
      step(
        "Great. I'll update the calendar.",
        "Cảm ơn vì sự linh hoạt.",
        "Thanks for being flexible.",
        ["Thank you for bending.", "I am flexible you."],
        "“Flexible” trong ngữ cảnh này là linh hoạt điều chỉnh lịch.",
      ),
    ],
  },
  {
    id: "travel",
    title: "Nhận phòng sau chuyến bay",
    role: "Bạn vừa đến quầy lễ tân khách sạn.",
    icon: "Plane",
    steps: [
      step(
        "Welcome! How can I help?",
        "Thông báo bạn đã đặt phòng.",
        "I have a reservation under Nguyen.",
        ["I reserve you for Nguyen.", "My room has a name."],
        "“Under + tên” cho biết tên dùng khi đặt phòng.",
      ),
      step(
        "Your room will be ready at three.",
        "Bạn muốn gửi hành lý.",
        "Could I leave my luggage here?",
        ["Can my luggage leave you?", "I leave here yesterday."],
        "“Could I …?” là cách xin phép lịch sự.",
      ),
      step(
        "Of course. Breakfast starts at seven.",
        "Hỏi bữa sáng có trong giá phòng không.",
        "Is breakfast included?",
        ["Does breakfast include me?", "Is breakfast inside?"],
        "“Included” nói dịch vụ đã được bao gồm trong giá.",
      ),
    ],
  },
  {
    id: "friends",
    title: "Rủ bạn đi chơi cuối tuần",
    role: "Bạn gặp một người bạn sau giờ làm.",
    icon: "Users",
    steps: [
      step(
        "Hey! How have you been?",
        "Hỏi kế hoạch cuối tuần.",
        "Pretty good! Any plans this weekend?",
        ["Where is your weekend?", "Your plans are my plans."],
        "“Any plans …?” là cách hỏi thân mật, rút gọn từ câu đầy đủ.",
      ),
      step(
        "Not yet. What did you have in mind?",
        "Gợi ý gặp nhau uống cà phê.",
        "Would you like to grab a coffee?",
        ["Do you like grabbing me?", "You get coffee now."],
        "“Grab a coffee” là cách nói thân mật về đi uống cà phê.",
      ),
      step(
        "Sounds great. Saturday at ten?",
        "Đồng ý và hẹn gặp tại đó.",
        "Perfect. I'll meet you there.",
        ["Perfect. I meet you yesterday.", "Perfect. You will there."],
        "“I’ll meet you there” xác nhận kế hoạch trong tương lai.",
      ),
    ],
  },
  {
    id: "shopping",
    title: "Đổi chiếc áo không vừa",
    role: "Bạn quay lại cửa hàng với hóa đơn.",
    icon: "ShoppingBag",
    steps: [
      step(
        "How can I help you today?",
        "Bạn muốn đổi áo sang cỡ khác.",
        "Can I exchange this for another size?",
        ["Can I change you a size?", "I am another size to you."],
        "“Exchange this for …” nói đổi món hiện có lấy món khác.",
      ),
      step(
        "Certainly. Do you have the receipt?",
        "Bạn đưa hóa đơn.",
        "Yes, here it is.",
        ["Yes, here it has.", "Yes, it is here me."],
        "“Here it is” dùng khi đưa một vật vừa được hỏi đến.",
      ),
      step(
        "Would you like to try the smaller one?",
        "Bạn muốn biết phòng thử đồ ở đâu.",
        "Yes, please. Where are the fitting rooms?",
        ["Where do the rooms fit?", "Where is fitting me?"],
        "“Fitting rooms” là phòng thử đồ; câu hỏi dùng “are” vì danh từ số nhiều.",
      ),
    ],
  },
  {
    id: "feelings",
    title: "Lắng nghe một ngày khó khăn",
    role: "Một người bạn đang chia sẻ chuyện buồn.",
    icon: "Heart",
    steps: [
      step(
        "I've had a really rough day.",
        "Mời bạn chia sẻ, không ép buộc.",
        "Would you like to talk about it?",
        ["Tell me everything right now.", "You should not feel anything."],
        "Hỏi “Would you like …?” để người kia được lựa chọn có chia sẻ hay không.",
      ),
      step(
        "My project got rejected after weeks of work.",
        "Thể hiện bạn hiểu cảm giác của họ.",
        "That must be really frustrating.",
        ["You must be a bad worker.", "It is nothing. Forget it."],
        "“That must be …” thể hiện sự đồng cảm dựa trên điều vừa nghe.",
      ),
      step(
        "Thanks for listening. I just needed to vent.",
        "Đáp lại bằng sự sẵn lòng lắng nghe.",
        "Of course. I'm here for you.",
        ["I am here because of your work.", "You need to listen to me now."],
        "“I’m here for you” thể hiện sự hỗ trợ và quan tâm.",
      ),
    ],
  },
  {
    id: "everyday",
    title: "Trễ hẹn một chút",
    role: "Bạn đang trên đường đến gặp bạn.",
    icon: "Sun",
    steps: [
      step(
        "Are you nearby?",
        "Báo rằng bạn sẽ đến hơi muộn.",
        "I'm running a little late.",
        ["I run later yesterday.", "You are making me late."],
        "“Running late” mô tả việc chậm hơn lịch dự kiến.",
      ),
      step(
        "No problem. How far away are you?",
        "Bạn sẽ đến trong mười phút.",
        "I'll be there in ten minutes.",
        ["I am there since ten minutes.", "I have ten minutes there."],
        "“In ten minutes” nghĩa là mười phút nữa, không phải mười phút trước.",
      ),
      step(
        "I'll wait inside the café.",
        "Cảm ơn vì đã chờ.",
        "Thanks for waiting. See you soon!",
        ["Thanks to wait me.", "Thank you to waited."],
        "Sau “Thanks for” dùng danh từ hoặc động từ thêm -ing.",
      ),
    ],
  },
  {
    id: "learning",
    title: "Hỏi lại khi chưa hiểu",
    role: "Bạn đang học cùng một người bạn.",
    icon: "GraduationCap",
    steps: [
      step(
        "This expression is a little tricky.",
        "Nhờ giải thích bằng từ dễ hơn.",
        "Could you explain it in simpler terms?",
        ["Could you simple the terms?", "You explain too badly."],
        "“In simpler terms” yêu cầu cách giải thích dễ hiểu, không phê phán người nói.",
      ),
      step(
        "It means to delay something until later.",
        "Xin một ví dụ.",
        "Could you give me an example?",
        ["Can you example me?", "You must an example."],
        "“Give someone an example” là kết hợp từ tự nhiên.",
      ),
      step(
        "For example: We put off the meeting.",
        "Diễn đạt lại để kiểm tra cách hiểu.",
        "So you mean you postponed it?",
        ["So the meeting put you?", "You mean the meeting is off me?"],
        "“So you mean …?” giúp xác nhận bạn hiểu đúng.",
      ),
    ],
  },
  {
    id: "home",
    title: "Báo vòi nước bị rò",
    role: "Bạn gọi cho người quản lý căn hộ.",
    icon: "House",
    steps: [
      step(
        "Hello, building management.",
        "Nêu vấn đề rõ ràng.",
        "The tap in my kitchen is leaking.",
        ["My kitchen drinks water.", "The water is tap me."],
        "Nêu vật bị lỗi và vị trí để người quản lý hiểu nhanh.",
      ),
      step(
        "We can send someone tomorrow.",
        "Hỏi khoảng thời gian đến.",
        "What time should I expect them?",
        ["What time I expect they?", "When you are them?"],
        "“Expect them” dùng để hỏi lúc nhân viên dự kiến đến.",
      ),
      step(
        "Between nine and eleven.",
        "Xác nhận bạn sẽ có nhà.",
        "That works. I'll be home.",
        ["I was home tomorrow.", "Home will be me."],
        "“I’ll be home” xác nhận sự có mặt trong tương lai.",
      ),
    ],
  },
  {
    id: "health",
    title: "Đặt lịch khám",
    role: "Bạn nói chuyện với lễ tân phòng khám; chỉ luyện ngôn ngữ.",
    icon: "Activity",
    steps: [
      step(
        "Good morning. How can I help?",
        "Bạn muốn đặt lịch gặp bác sĩ.",
        "I'd like to book an appointment.",
        ["I want you to be sick.", "I am booking your doctor away."],
        "“Book an appointment” là đặt lịch hẹn.",
      ),
      step(
        "What seems to be the problem?",
        "Mô tả triệu chứng và thời điểm.",
        "I've had a sore throat since yesterday.",
        ["I have sore yesterday since.", "My throat is yesterday."],
        "Hiện tại hoàn thành với “since” nói tình trạng bắt đầu trước đó và còn kéo dài.",
      ),
      step(
        "We have an opening at ten tomorrow.",
        "Đồng ý giờ hẹn.",
        "Ten tomorrow works for me, thank you.",
        ["Tomorrow worked yesterday.", "You must be ten."],
        "Nhắc lại thời gian giúp xác nhận chính xác lịch hẹn.",
      ),
    ],
  },
  {
    id: "tech",
    title: "Cuộc gọi bị mất tiếng",
    role: "Bạn đang họp trực tuyến.",
    icon: "Laptop",
    steps: [
      step(
        "Can everyone hear me?",
        "Bạn nghe âm thanh chập chờn.",
        "Your audio is breaking up.",
        ["Your voice is broken forever.", "You break my hearing."],
        "“Breaking up” trong cuộc gọi là âm thanh bị ngắt quãng.",
      ),
      step(
        "Let me switch networks. Is that better?",
        "Báo đã nghe rõ.",
        "Yes, I can hear you clearly now.",
        ["Yes, I hear clearly you before.", "You can hear myself."],
        "“Clearly now” xác nhận vấn đề vừa được cải thiện.",
      ),
      step(
        "Great. Let's look at the document.",
        "Nhờ gửi đường dẫn.",
        "Could you send me the link?",
        ["Can you link me sent?", "Could you sending the linked?"],
        "“Send someone something” là cấu trúc gửi thứ gì cho ai.",
      ),
    ],
  },
  {
    id: "phone",
    title: "Để lại lời nhắn",
    role: "Bạn gọi đến văn phòng để tìm Alex.",
    icon: "Phone",
    steps: [
      step(
        "Good afternoon, Green Studio.",
        "Xin gặp Alex.",
        "May I speak to Alex, please?",
        ["May Alex speak me?", "I speak you Alex now."],
        "“May I speak to …?” là cách lịch sự để xin gặp ai qua điện thoại.",
      ),
      step(
        "I'm afraid Alex is in a meeting.",
        "Nhờ Alex gọi lại.",
        "Could you ask Alex to call me back?",
        ["Could Alex ask back me?", "Call me Alex back you."],
        "“Ask someone to do something” dùng để nhờ chuyển yêu cầu.",
      ),
      step(
        "Of course. Can I take your name?",
        "Giới thiệu tên và cảm ơn.",
        "My name is Minh. Thanks for your help.",
        ["My name has Minh.", "I am the name with Minh."],
        "Cung cấp đúng thông tin người nhận cần để chuyển lời nhắn.",
      ),
    ],
  },
  {
    id: "plans",
    title: "Một lịch hẹn vừa với cả hai",
    role: "Bạn đang sắp xếp một buổi gặp.",
    icon: "CalendarDays",
    steps: [
      step(
        "When are you free this week?",
        "Bạn rảnh sau sáu giờ.",
        "Any day after six works for me.",
        ["I free since six future.", "Six is working at my day."],
        "“Any day after six” cung cấp cả ngày linh hoạt và giới hạn giờ.",
      ),
      step(
        "How about Thursday at seven?",
        "Bạn đã có hẹn thứ Năm.",
        "I've already made plans for Thursday.",
        ["I make already Thursday past.", "Thursday has me plans."],
        "“Already made plans” giải thích bạn đã sắp xếp việc khác.",
      ),
      step(
        "Friday, then?",
        "Đồng ý và xác nhận.",
        "Friday at seven sounds good.",
        ["Friday sounds at me seven.", "Seven was Friday."],
        "Lặp lại cả ngày và giờ để tránh hiểu nhầm.",
      ),
    ],
  },
  {
    id: "help",
    title: "Nhận nhầm món hàng",
    role: "Bạn liên hệ bộ phận chăm sóc khách hàng.",
    icon: "LifeBuoy",
    steps: [
      step(
        "How can I assist you?",
        "Bạn nhận được món khác đơn đã đặt.",
        "I received the wrong item.",
        ["You are a wrong item.", "My item wronged me."],
        "Nêu sự việc cụ thể giúp hỗ trợ xử lý nhanh.",
      ),
      step(
        "I'm sorry about that. Could you send a photo?",
        "Bạn sẽ gửi ảnh ngay.",
        "Of course. I'll send one now.",
        ["I sent one tomorrow.", "Photo can you me."],
        "“One” thay cho “a photo” để tránh lặp danh từ.",
      ),
      step(
        "We can send a replacement or issue a refund.",
        "Bạn muốn hoàn tiền.",
        "I'd prefer a refund, please.",
        ["I refund you preferred.", "I prefer you pay everything."],
        "“I’d prefer …” bày tỏ lựa chọn lịch sự giữa các phương án.",
      ),
    ],
  },
  {
    id: "entertainment",
    title: "Tìm một bộ phim cuối tuần",
    role: "Bạn đang hỏi gợi ý phim từ bạn bè.",
    icon: "Music",
    steps: [
      step(
        "Have you seen The Quiet Journey?",
        "Bạn chưa xem và muốn nghe đánh giá.",
        "Not yet. Would you recommend it?",
        ["Not yet. You recommend me are?", "No. What do you order?"],
        "“Would you recommend it?” hỏi liệu tác phẩm có đáng xem không.",
      ),
      step(
        "Definitely! The ending is incredible.",
        "Nhắc bạn đừng tiết lộ kết thúc.",
        "Don't spoil the ending!",
        ["Do not end my spoil.", "You should finish me."],
        "“Spoil the ending” là tiết lộ làm mất bất ngờ.",
      ),
      step(
        "No spoilers, I promise. Want to watch it together?",
        "Bạn muốn tham gia.",
        "I'd love to. When are you free?",
        ["I love free you when.", "I want to watch you free."],
        "“I’d love to” thể hiện sự hào hứng nhận lời mời.",
      ),
    ],
  },
  {
    id: "interview",
    title: "Cuộc phỏng vấn đầu tiên",
    role: "Bạn đang trao đổi với người phỏng vấn.",
    icon: "Award",
    steps: [
      step(
        "Could you tell me a little about yourself?",
        "Giới thiệu kinh nghiệm cụ thể.",
        "I have three years of experience in customer service.",
        [
          "I am very perfect at everything.",
          "You can read everything yourself.",
        ],
        "Thông tin cụ thể giúp người nghe hiểu nền tảng nghề nghiệp của bạn.",
      ),
      step(
        "Why are you interested in this role?",
        "Bạn muốn nhận thêm trách nhiệm.",
        "I'm ready to take on more responsibility.",
        ["I want you to take my job.", "I am responsible to more take."],
        "“Take on responsibility” là đảm nhận trách nhiệm.",
      ),
      step(
        "Do you have any questions for us?",
        "Hỏi cách đánh giá thành công.",
        "What would success look like in this role?",
        ["Why are you asking me things?", "How much success you look?"],
        "Câu hỏi giúp hiểu kỳ vọng và cách đánh giá ở vị trí ứng tuyển.",
      ),
    ],
  },
];
